Update ClassLoaderFixer to v2
FabricCompatibilityLayers/Fabricated-Legacy-Forge pull request #29
Opened 2024-07-04 15:59 UTC by ThexXTURBOXx

Today I released ClassLoaderFixer 2. Most changes here are not really necessary, but I still applied some of them to be consistent :)
By the way, this exact same class also works for every version up to 1.4.5 - so feel free to incorporate it in every version up until then.
At least `public static String FIXER_VERSION = "2";` would be important to add everywhere to tell Block Helper to shut up (otherwise it warns the user everytime that he needs a proper `RelaunchClassLoader` implementation - even though it is indeed fine)

2024-07-04 17:37 UTC, halotroop2288 requested changes
A lot of these style changes are unnecessary. It seems like very little of this was actually related to updating the dependency.

2024-07-04 17:37 UTC, halotroop2288 commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.parent = this.getClass().getClassLoader();
C'mon man.

2024-07-04 17:37 UTC, halotroop2288 commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.addClassLoaderExclusion("com.llamalad7.mixinextras.");
Did these become static? If not, just leave it be...

2024-07-04 17:37 UTC, halotroop2288 commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> +//                try
What's the point in adding *yet more* commented out code?

2024-07-04 17:37 UTC, halotroop2288 commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> +import java.util.jar.Attributes.Name;
Seems like an unnecessary style chane, to change this to an inner class import.

2024-07-04 17:37 UTC, halotroop2288 commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.sources.add(url);
Again, why would you remove this? It's making the type of call clearer.

2024-07-04 17:46 UTC, ThexXTURBOXx commented
> Most changes here are not really necessary, but I still applied some of them to be consistent

2024-07-04 18:00 UTC, ThexXTURBOXx reviewed
Overall, feel free to just close this PR without any comment or feel free to merge it. It's your decision. As already said in the description of this PR: Incrementing the `FIXER_VERSION` to `2` is the only important change in this PR. The rest would just have made the codebase more consistent with the original ClassLoaderFixer.
And as already said, just add the `FIXER_VERSION` line to all the versions between 1.3.1 and 1.4.5 (since the first Forge version for 1.4.6 already fixed it and makes ClassLoaderFixer unnecessary).

2024-07-04 18:00 UTC, ThexXTURBOXx commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> +import java.util.jar.Attributes.Name;
Unnecessary? Might be. Just copy-pasted from my ClassLoaderFixer source code.

2024-07-04 18:00 UTC, ThexXTURBOXx commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.parent = this.getClass().getClassLoader();
Tbh, get off your high horse. If you think this is unnecessary, just close this PR without any comment. But don't spend your time writing such comments if the explanation is already there in the premise of the PR.

2024-07-04 18:00 UTC, ThexXTURBOXx commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.addClassLoaderExclusion("com.llamalad7.mixinextras.");
Same here

2024-07-04 18:00 UTC, ThexXTURBOXx commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> +//                try
To keep the codebase consistent. Explains the working principle behind ClassLoaderFixer. If it's unnecessary, then this entire commented out code snippet should have already been removed ages ago

2024-07-04 18:00 UTC, ThexXTURBOXx commented on src/main/java/cpw/mods/fml/relauncher/RelaunchClassLoader.java
> -        this.sources.add(url);
Same as one of the above here

2024-08-06 15:30 UTC, thecatcore commented
Thanks for the contribution.
I'm currently working on a possible v2 of Fabricated-Legacy-Forge, if I'm successful with the rewrite I'll include it in v2 directly.

2024-08-06 16:14 UTC, ThexXTURBOXx commented
Perfect, thank you very much and good luck! :)
Let me know if you need something!

2025-05-04 13:55 UTC, thecatcore commented
Hello, I've made a lot of progress on the rewrite, can you open a new PR targeting the `rewrite/1.3.2` branch instead?

2025-05-04 13:55 UTC, closed without merging

2025-05-04 19:39 UTC, ThexXTURBOXx commented
Of course, PR incoming! :)